<?php

return [

    'company_types' => [
        'Civil Contractor',
        'Mechanical Contractor',
        'Electrical Contractor',
        'Plumbing Contractor',
        'Fire Fighting Contractor',
        'Lifting Contractor',
        'Scaffolding Contractor',
        'Housekeeping Contractor',
        'Waste Contractor',
        'Safety Services Contractor',
        'General Contractor',
        'Vendor / Supplier',
        'Transport Contractor',
        'Fit-Out Contractor',
        'Rail / Infrastructure Contractor',
        'Other',
    ],

    'scopes_of_work' => [
        'Civil Works',
        'Mechanical Works',
        'Electrical Works',
        'Plumbing',
        'Scaffolding',
        'Lifting Operations',
        'Welding & Fabrication',
        'Driving / Logistics',
        'Waste Disposal',
        'Housekeeping',
        'Maintenance',
        'Emergency Support',
        'Rail / Track Works',
        'Fit-Out',
        'Fire Protection',
        'HVAC',
        'Other',
    ],

    'document_types' => [
        'Trade License',
        'Company Registration Certificate',
        'Tax / VAT Certificate',
        'Public Liability Insurance',
        'Workers Compensation Insurance',
        'Vehicle Insurance',
        'Equipment Insurance',
        'Safety Certification',
        'Environmental Permit',
        'Transport Permit',
        'Waste Disposal Authorization',
        'ISO Certification',
        'Contract Agreement',
        'Bank Guarantee',
        'Performance Bond',
        'Other Approval',
    ],

    'contact_roles' => [
        'Primary Contact',
        'Site Supervisor',
        'HSE / Safety Representative',
        'Project Manager',
        'Operations Manager',
        'Emergency Contact',
        'Finance / Commercial',
        'HR Representative',
        'Other',
    ],

    'contractor_statuses' => [
        'Draft',
        'Under Review',
        'Approved',
        'Active',
        'Inactive',
        'Suspended',
        'Expired',
        'Rejected',
        'Blacklisted',
    ],

    'compliance_statuses' => [
        'Compliant',
        'Partially Compliant',
        'Non-Compliant',
        'Under Review',
        'Suspended',
    ],

    'document_statuses' => [
        'Valid',
        'Expiring Soon',
        'Expired',
        'Under Review',
        'Rejected',
    ],

    'expiry_warning_days' => 30,
    'expiry_critical_days' => 7,
];
