<?php

return [
    'categories' => [

        // ── LIFTING & ELEVATED WORK ──────────────────────
        [
            'key'            => 'forklift',
            'label'          => 'Forklifts',
            'group'          => 'Lifting & Elevated Work',
            'icon'           => 'forklift',
            'color'          => '#DC2626',
            'light_color'    => '#FEE2E2',
            'text_color'     => '#991B1B',
            'has_plate'      => true,
            'has_swl'        => true,
            'has_tuv'        => true,
            'has_cert'       => true,
            'insp_freq_days' => 1,
            'tuv_freq_days'  => 365,
            'description'    => 'Counterbalance and reach forklifts',
            'sort_order'     => 10,
            'template_type'  => 'heavy_equipment',
        ],
        [
            'key'            => 'scissor_lift',
            'label'          => 'Scissor Lifts',
            'group'          => 'Lifting & Elevated Work',
            'icon'           => 'maximize-2',
            'color'          => '#7C3AED',
            'light_color'    => '#EDE9FE',
            'text_color'     => '#5B21B6',
            'has_plate'      => true,
            'has_swl'        => true,
            'has_tuv'        => true,
            'has_cert'       => true,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => 180,
            'description'    => 'Electric and rough-terrain scissor lifts',
            'sort_order'     => 20,
            'template_type'  => 'heavy_equipment',
        ],
        [
            'key'            => 'man_lift',
            'label'          => 'Man Lifts / Man Baskets',
            'group'          => 'Lifting & Elevated Work',
            'icon'           => 'user-check',
            'color'          => '#065F46',
            'light_color'    => '#D1FAE5',
            'text_color'     => '#047857',
            'has_plate'      => true,
            'has_swl'        => true,
            'has_tuv'        => true,
            'has_cert'       => true,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => 180,
            'description'    => 'Vertical personnel lifts and man baskets',
            'sort_order'     => 30,
            'template_type'  => 'heavy_equipment',
        ],
        [
            'key'            => 'boom_lift',
            'label'          => 'Boom Lifts / Boom Trucks',
            'group'          => 'Lifting & Elevated Work',
            'icon'           => 'trending-up',
            'color'          => '#B45309',
            'light_color'    => '#FEF3C7',
            'text_color'     => '#92400E',
            'has_plate'      => true,
            'has_swl'        => true,
            'has_tuv'        => true,
            'has_cert'       => true,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => 180,
            'description'    => 'Articulating and straight boom lifts',
            'sort_order'     => 40,
            'template_type'  => 'heavy_equipment',
        ],

        // ── SAFETY EQUIPMENT ────────────────────────────
        [
            'key'            => 'fire_extinguisher',
            'label'          => 'Fire Extinguishers',
            'group'          => 'Safety Equipment',
            'icon'           => 'flame',
            'color'          => '#EA580C',
            'light_color'    => '#FFF7ED',
            'text_color'     => '#C2410C',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => true,
            'insp_freq_days' => 30,
            'tuv_freq_days'  => null,
            'description'    => 'CO2, dry powder, foam, water extinguishers',
            'sort_order'     => 50,
            'template_type'  => 'fire_extinguisher',
        ],
        [
            'key'            => 'full_body_harness',
            'label'          => 'Full Body Harnesses',
            'group'          => 'Safety Equipment',
            'icon'           => 'shield',
            'color'          => '#BE185D',
            'light_color'    => '#FCE7F3',
            'text_color'     => '#9D174D',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'Safety harnesses and fall arrest equipment',
            'sort_order'     => 60,
            'template_type'  => 'harness',
        ],
        [
            'key'            => 'ladder',
            'label'          => 'Ladders',
            'group'          => 'Safety Equipment',
            'icon'           => 'align-justify',
            'color'          => '#0369A1',
            'light_color'    => '#E0F2FE',
            'text_color'     => '#075985',
            'has_plate'      => false,
            'has_swl'        => true,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'Step ladders, extension ladders, roof ladders',
            'sort_order'     => 70,
            'template_type'  => 'light_equipment',
        ],

        // ── POWER TOOLS ─────────────────────────────────
        [
            'key'            => 'welding_machine',
            'label'          => 'Welding Machines',
            'group'          => 'Power Tools',
            'icon'           => 'zap',
            'color'          => '#4F46E5',
            'light_color'    => '#EEF2FF',
            'text_color'     => '#4338CA',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'MIG, TIG, arc welding machines',
            'sort_order'     => 80,
            'template_type'  => 'power_tool',
        ],
        [
            'key'            => 'power_tool',
            'label'          => 'Power Tools',
            'group'          => 'Power Tools',
            'icon'           => 'settings',
            'color'          => '#374151',
            'light_color'    => '#F3F4F6',
            'text_color'     => '#1F2937',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'Drills, impact drivers, jigsaws',
            'sort_order'     => 90,
            'template_type'  => 'power_tool',
        ],
        [
            'key'            => 'grinder',
            'label'          => 'Grinders',
            'group'          => 'Power Tools',
            'icon'           => 'circle',
            'color'          => '#92400E',
            'light_color'    => '#FEF3C7',
            'text_color'     => '#78350F',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'Angle grinders, bench grinders',
            'sort_order'     => 100,
            'template_type'  => 'power_tool',
        ],
        [
            'key'            => 'cutter',
            'label'          => 'Cutters',
            'group'          => 'Power Tools',
            'icon'           => 'scissors',
            'color'          => '#0F766E',
            'light_color'    => '#CCFBF1',
            'text_color'     => '#0D9488',
            'has_plate'      => false,
            'has_swl'        => false,
            'has_tuv'        => false,
            'has_cert'       => false,
            'insp_freq_days' => 7,
            'tuv_freq_days'  => null,
            'description'    => 'Disc cutters, pipe cutters, bolt cutters',
            'sort_order'     => 110,
            'template_type'  => 'power_tool',
        ],
    ],

    // Template field definitions per template_type
    'templates' => [

        'heavy_equipment' => [
            'required_fields' => ['equipment_name', 'plate_number', 'serial_number', 'make_model', 'onboarding_date'],
            'optional_fields' => ['swl', 'load_capacity_tons', 'certificate_number', 'certificate_expiry', 'checker_number', 'tuv_inspection_date', 'tuv_expiry_date', 'internal_inspection_date', 'next_inspection_date', 'inspected_by', 'location_area', 'notes'],
            'excel_columns' => ['Equipment Name', 'Plate Number', 'Serial Number', 'Make/Model', 'Onboarding Date', 'SWL', 'Capacity (Tons)', 'Certificate Number', 'Certificate Expiry', 'Checker Number', 'TUV Inspection Date', 'TUV Expiry Date', 'Internal Inspection Date', 'Next Inspection Date', 'Inspected By', 'Location/Area', 'Status', 'Notes'],
        ],

        'fire_extinguisher' => [
            'required_fields' => ['equipment_name', 'extinguisher_type', 'onboarding_date'],
            'optional_fields' => ['serial_number', 'weight_kg', 'civil_defense_tag', 'certificate_number', 'internal_inspection_date', 'next_inspection_date', 'expiry_date', 'inspected_by', 'location_area', 'notes'],
            'excel_columns' => ['Name/ID', 'Extinguisher Type', 'Onboarding Date', 'Serial Number', 'Weight (KG)', 'Civil Defense Tag (Y/N)', 'Certificate Number', 'Internal Inspection Date', 'Next Inspection Date', 'Expiry Date', 'Inspected By', 'Location/Area', 'Status', 'Notes'],
        ],

        'harness' => [
            'required_fields' => ['equipment_name', 'onboarding_date'],
            'optional_fields' => ['serial_number', 'manufacture_date', 'retirement_date', 'internal_inspection_date', 'next_inspection_date', 'last_drop_arrest', 'drop_arrest_date', 'inspected_by', 'assigned_to', 'condition', 'notes'],
            'excel_columns' => ['Name/ID', 'Serial Number', 'Onboarding Date', 'Manufacture Date', 'Retirement Date', 'Internal Inspection Date', 'Next Inspection Date', 'Drop/Fall Arrest (Y/N)', 'Inspected By', 'Assigned To', 'Condition', 'Status', 'Notes'],
        ],

        'light_equipment' => [
            'required_fields' => ['equipment_name', 'onboarding_date'],
            'optional_fields' => ['serial_number', 'make_model', 'swl', 'certificate_number', 'internal_inspection_date', 'next_inspection_date', 'expiry_date', 'inspected_by', 'condition', 'toolbox_tag_colour', 'notes'],
            'excel_columns' => ['Name/ID', 'Serial Number', 'Make/Model', 'Onboarding Date', 'SWL', 'Certificate Number', 'Internal Inspection Date', 'Next Inspection Date', 'Expiry Date', 'Inspected By', 'Condition', 'Code Colour', 'Status', 'Notes'],
        ],

        'power_tool' => [
            'required_fields' => ['equipment_name', 'onboarding_date'],
            'optional_fields' => ['serial_number', 'make_model', 'voltage_rating', 'internal_inspection_date', 'next_inspection_date', 'electrical_test_date', 'electrical_test_expiry', 'inspected_by', 'condition', 'toolbox_tag_colour', 'notes'],
            'excel_columns' => ['Name/ID', 'Serial Number', 'Make/Model', 'Onboarding Date', 'Voltage Rating', 'Internal Inspection Date', 'Next Inspection Date', 'Electrical Test Date', 'Electrical Test Expiry', 'Inspected By', 'Condition', 'Code Colour', 'Status', 'Notes'],
        ],
    ],
];
