<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Poster;
use App\Models\PosterLink;
use App\Models\PosterTemplate;

class PosterTestDataSeeder extends Seeder
{
    public function run(): void
    {
        $templates = PosterTemplate::active()->pluck('id', 'name');
        $user = \App\Models\User::first();
        $userId = $user?->id;

        $posters = [
            [
                'title'           => 'Work at Height Safety',
                'subtitle'        => 'Fall Prevention Guidelines',
                'category'        => 'Safety Awareness',
                'poster_type'     => 'Warning Poster',
                'topic'           => 'Work at Height',
                'headline'        => 'PROTECT YOURSELF FROM FALLS',
                'subheadline'     => 'Every height is a danger — stay secured',
                'main_body_text'  => 'Working at height remains one of the leading causes of workplace fatalities. Always ensure proper fall protection equipment is in use before starting any elevated work.',
                'bullet_points'   => ['Always wear a safety harness', 'Inspect equipment before use', 'Secure all tools and materials', 'Never work alone at height', 'Report unsafe conditions immediately'],
                'warning_text'    => 'FALL HAZARD — Harness mandatory above 2 meters',
                'call_to_action'  => 'Report Unsafe Conditions',
                'footer_text'     => 'Safety Department — KAEC Project',
                'template_id'     => $templates['Warning Alert - Bold'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'warning_red',
                'font_size'       => 'Large',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'All Workers',
                'priority'        => 'High',
                'site'            => 'KAEC',
                'area'            => 'Zone A',
                'status'          => 'Published',
                'published_at'    => now()->subDays(5),
                'published_by'    => $user?->full_name ?? 'Admin',
                'view_count'      => 47,
                'download_count'  => 12,
                'print_count'     => 8,
            ],
            [
                'title'           => 'PPE Compliance Reminder',
                'subtitle'        => 'Personal Protective Equipment',
                'category'        => 'Compliance Reminder',
                'poster_type'     => 'Compliance Poster',
                'topic'           => 'PPE',
                'headline'        => 'PPE IS NOT OPTIONAL',
                'subheadline'     => 'Your safety gear saves lives',
                'main_body_text'  => 'All personnel must wear the required PPE at all times while in designated work zones. Violations will be documented.',
                'bullet_points'   => ['Hard hat', 'Safety glasses', 'High-visibility vest', 'Steel-toe boots', 'Gloves as required'],
                'call_to_action'  => 'Check Your PPE Now',
                'footer_text'     => 'EHS Department',
                'template_id'     => $templates['PPE Requirement'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'trust_blue',
                'font_size'       => 'Medium',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'All Workers',
                'priority'        => 'High',
                'site'            => 'KAEC',
                'status'          => 'Published',
                'published_at'    => now()->subDays(3),
                'published_by'    => $user?->full_name ?? 'Admin',
                'view_count'      => 35,
                'download_count'  => 9,
            ],
            [
                'title'           => 'Fire Safety Week Campaign',
                'subtitle'        => 'Know the Drill — Save a Life',
                'category'        => 'Campaign',
                'poster_type'     => 'Event Poster',
                'topic'           => 'Fire Safety',
                'headline'        => 'FIRE SAFETY WEEK',
                'subheadline'     => 'March 15-22, 2026',
                'main_body_text'  => 'Join us for Fire Safety Week! Participate in fire drills, learn about fire extinguisher use, and understand evacuation procedures.',
                'bullet_points'   => ['Monday: Fire drill walkthrough', 'Tuesday: Extinguisher training', 'Wednesday: Evacuation simulation', 'Thursday: Quiz and prizes', 'Friday: Certificate ceremony'],
                'call_to_action'  => 'Sign Up Today',
                'quote_or_slogan' => 'Prevention is better than firefighting.',
                'footer_text'     => 'Fire Safety Campaign 2026',
                'template_id'     => $templates['Campaign Poster - Two Column'] ?? null,
                'orientation'     => 'Landscape',
                'theme_key'       => 'caution_amber',
                'font_size'       => 'Large',
                'text_alignment'  => 'Left',
                'print_size'      => 'A3',
                'target_audience' => 'All Workers',
                'priority'        => 'Medium',
                'site'            => 'KAEC',
                'status'          => 'Approved',
                'view_count'      => 20,
            ],
            [
                'title'           => 'Emergency Evacuation Procedure',
                'category'        => 'Emergency / ERP',
                'poster_type'     => 'Emergency Poster',
                'topic'           => 'Emergency Response',
                'headline'        => 'EMERGENCY EVACUATION',
                'subheadline'     => 'Know your exit — Know your assembly point',
                'main_body_text'  => 'In the event of an emergency alarm, cease all work immediately and proceed to the nearest exit. Do not use elevators.',
                'bullet_points'   => ['Stop all work', 'Alert nearby workers', 'Proceed to nearest exit', 'Do NOT use elevators', 'Report to assembly point', 'Wait for headcount'],
                'warning_text'    => 'EMERGENCY — Follow instructions immediately',
                'footer_text'     => 'Emergency Response Team',
                'template_id'     => $templates['Emergency Procedure'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'warning_red',
                'font_size'       => 'Extra Large',
                'text_alignment'  => 'Center',
                'print_size'      => 'A3',
                'target_audience' => 'All Workers',
                'priority'        => 'Critical',
                'site'            => 'KAEC',
                'status'          => 'Published',
                'published_at'    => now()->subDays(10),
                'published_by'    => $user?->full_name ?? 'Admin',
                'view_count'      => 89,
                'download_count'  => 25,
                'print_count'     => 18,
            ],
            [
                'title'           => 'Heat Stress Prevention',
                'subtitle'        => 'Stay Hydrated — Stay Safe',
                'category'        => 'Safety Awareness',
                'poster_type'     => 'Awareness Poster',
                'topic'           => 'Heat Stress',
                'headline'        => 'BEAT THE HEAT',
                'subheadline'     => 'Recognize the signs before it is too late',
                'main_body_text'  => 'Heat-related illness can be fatal. Know the signs: dizziness, nausea, rapid heartbeat, confusion. Take regular breaks and drink water every 20 minutes.',
                'bullet_points'   => ['Drink water every 20 minutes', 'Take shade breaks', 'Wear lightweight clothing', 'Watch for symptoms', 'Buddy system — watch each other'],
                'call_to_action'  => 'Hydration Station Locations',
                'footer_text'     => 'HSE Department — Summer Safety',
                'template_id'     => $templates['Safety Awareness - Hero'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'caution_amber',
                'font_size'       => 'Large',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'All Workers',
                'priority'        => 'High',
                'site'            => 'KAEC',
                'area'            => 'Outdoor Zones',
                'status'          => 'Draft',
                'view_count'      => 5,
            ],
            [
                'title'           => 'Toolbox Talk Schedule',
                'category'        => 'Training',
                'poster_type'     => 'Announcement Poster',
                'topic'           => 'Manual Handling',
                'headline'        => 'WEEKLY TOOLBOX TALKS',
                'main_body_text'  => 'Attend your weekly toolbox talk every Sunday at 7:00 AM. Topics rotate monthly.',
                'call_to_action'  => 'Check Schedule',
                'footer_text'     => 'Training Department',
                'template_id'     => $templates['Training Reminder - Minimal'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'trust_blue',
                'font_size'       => 'Medium',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'Supervisors',
                'priority'        => 'Medium',
                'site'            => 'KAEC',
                'status'          => 'Under Review',
                'view_count'      => 8,
            ],
            [
                'title'           => 'Zero Incidents Month',
                'subtitle'        => 'Together We Can',
                'category'        => 'Motivation / Engagement',
                'poster_type'     => 'Motivational Poster',
                'headline'        => 'ZERO IS OUR GOAL',
                'subheadline'     => '30 days without incident — keep it going!',
                'quote_or_slogan' => 'Safety is not a slogan, it is a way of life.',
                'footer_text'     => 'Safety First — Always',
                'template_id'     => $templates['Motivational - Clean'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'safety_green',
                'font_size'       => 'Extra Large',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'All Workers',
                'priority'        => 'Low',
                'site'            => 'KAEC',
                'status'          => 'Published',
                'published_at'    => now()->subDays(1),
                'published_by'    => $user?->full_name ?? 'Admin',
                'view_count'      => 15,
                'download_count'  => 4,
            ],
            [
                'title'           => 'Permit to Work Awareness',
                'category'        => 'Permit Awareness',
                'poster_type'     => 'Instruction Poster',
                'topic'           => 'Permit Compliance',
                'headline'        => 'NO PERMIT = NO WORK',
                'main_body_text'  => 'All hot work, confined space entry, and electrical isolation tasks require a valid permit to work before commencement.',
                'bullet_points'   => ['Obtain permit before work', 'Display permit at worksite', 'Follow all conditions', 'Close out on completion'],
                'warning_text'    => 'Working without a permit is a serious violation',
                'footer_text'     => 'Permit Office — Ext. 5500',
                'template_id'     => $templates['Permit Awareness'] ?? null,
                'orientation'     => 'Portrait',
                'theme_key'       => 'professional_dark',
                'font_size'       => 'Large',
                'text_alignment'  => 'Center',
                'print_size'      => 'A4',
                'target_audience' => 'Contractors',
                'priority'        => 'High',
                'site'            => 'KAEC',
                'status'          => 'Archived',
                'view_count'      => 60,
                'download_count'  => 15,
                'print_count'     => 10,
            ],
        ];

        foreach ($posters as $data) {
            $data['created_by'] = $userId;
            $poster = Poster::create($data);
            $poster->logHistory('Poster Created', null, $data['status']);

            // Create empty link record
            PosterLink::create(['poster_id' => $poster->id]);
        }
    }
}
