import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, WidthType,
} from 'docx';
import { saveAs } from 'file-saver';

export interface ReportMeta {
  title: string;
  period: string;
  dateRange: string;
  generatedAt: string;
  generatedBy: string;
  filters?: string;
}

export interface ExportData {
  meta: ReportMeta;
  summaryRows: { label: string; value: string | number }[];
  tableHeaders: string[];
  tableRows: (string | number)[][];
}

// ─── Excel (.xlsx) ──────────────────────────────────
export function exportExcel(data: ExportData, filename: string) {
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryAoa = [
    [data.meta.title],
    [`Period: ${data.meta.period}`],
    [`Date Range: ${data.meta.dateRange}`],
    [`Generated: ${data.meta.generatedAt}`],
    [`Generated By: ${data.meta.generatedBy}`],
    ...(data.meta.filters ? [[`Filters: ${data.meta.filters}`]] : []),
    [],
    ['Metric', 'Value'],
    ...data.summaryRows.map(r => [r.label, r.value]),
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryAoa);
  wsSummary['!cols'] = [{ wch: 30 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // Detail sheet
  const detailAoa = [data.tableHeaders, ...data.tableRows];
  const wsDetail = XLSX.utils.aoa_to_sheet(detailAoa);
  wsDetail['!cols'] = data.tableHeaders.map(() => ({ wch: 18 }));
  XLSX.utils.book_append_sheet(wb, wsDetail, 'Detailed Records');

  XLSX.writeFile(wb, `${filename}.xlsx`);
}

// ─── CSV (.csv) ─────────────────────────────────────
export function exportCSV(data: ExportData, filename: string) {
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet([data.tableHeaders, ...data.tableRows]);
  XLSX.utils.book_append_sheet(wb, ws, 'Data');
  XLSX.writeFile(wb, `${filename}.csv`, { bookType: 'csv' });
}

// ─── PDF (.pdf) ─────────────────────────────────────
export function exportPDF(data: ExportData, filename: string) {
  const doc = new jsPDF({ orientation: 'landscape' });

  // Title
  doc.setFontSize(18);
  doc.text(data.meta.title, 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Period: ${data.meta.period}  |  Date Range: ${data.meta.dateRange}`, 14, 28);
  doc.text(`Generated: ${data.meta.generatedAt}  |  By: ${data.meta.generatedBy}`, 14, 34);
  if (data.meta.filters) doc.text(`Filters: ${data.meta.filters}`, 14, 40);
  doc.setTextColor(0);

  // Summary table
  const summaryStartY = data.meta.filters ? 48 : 42;
  doc.setFontSize(13);
  doc.text('Summary', 14, summaryStartY);

  autoTable(doc, {
    startY: summaryStartY + 4,
    head: [['Metric', 'Value']],
    body: data.summaryRows.map(r => [r.label, String(r.value)]),
    theme: 'grid',
    headStyles: { fillColor: [30, 64, 175], fontSize: 9 },
    styles: { fontSize: 9 },
    margin: { left: 14 },
    tableWidth: 120,
  });

  // Detailed table
  const afterSummary = (doc as any).lastAutoTable?.finalY ?? summaryStartY + 60;
  doc.setFontSize(13);
  doc.text('Detailed Records', 14, afterSummary + 12);

  autoTable(doc, {
    startY: afterSummary + 16,
    head: [data.tableHeaders],
    body: data.tableRows.map(r => r.map(String)),
    theme: 'grid',
    headStyles: { fillColor: [30, 64, 175], fontSize: 8 },
    styles: { fontSize: 7, cellPadding: 2 },
    margin: { left: 14 },
  });

  doc.save(`${filename}.pdf`);
}

// ─── Word (.docx) ───────────────────────────────────
export async function exportWord(data: ExportData, filename: string) {
  const boldRun = (text: string) => new TextRun({ text, bold: true });

  const summaryHeaderRow = new TableRow({
    children: [
      new TableCell({ children: [new Paragraph({ children: [boldRun('Metric')] })], width: { size: 60, type: WidthType.PERCENTAGE } }),
      new TableCell({ children: [new Paragraph({ children: [boldRun('Value')] })], width: { size: 40, type: WidthType.PERCENTAGE } }),
    ],
  });

  const summaryDataRows = data.summaryRows.map(r =>
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph(r.label)] }),
        new TableCell({ children: [new Paragraph(String(r.value))] }),
      ],
    }),
  );

  const detailHeaderRow = new TableRow({
    children: data.tableHeaders.map(h =>
      new TableCell({ children: [new Paragraph({ children: [boldRun(h)] })] }),
    ),
  });

  const detailDataRows = data.tableRows.slice(0, 200).map(row =>
    new TableRow({
      children: row.map(cell =>
        new TableCell({ children: [new Paragraph(String(cell ?? ''))] }),
      ),
    }),
  );

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ text: data.meta.title, heading: HeadingLevel.HEADING_1 }),
        new Paragraph(`Period: ${data.meta.period}`),
        new Paragraph(`Date Range: ${data.meta.dateRange}`),
        new Paragraph(`Generated: ${data.meta.generatedAt}`),
        new Paragraph(`Generated By: ${data.meta.generatedBy}`),
        ...(data.meta.filters ? [new Paragraph(`Filters: ${data.meta.filters}`)] : []),
        new Paragraph(''),
        new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_2 }),
        new Table({ rows: [summaryHeaderRow, ...summaryDataRows], width: { size: 100, type: WidthType.PERCENTAGE } }),
        new Paragraph(''),
        new Paragraph({ text: 'Detailed Records', heading: HeadingLevel.HEADING_2 }),
        new Table({ rows: [detailHeaderRow, ...detailDataRows], width: { size: 100, type: WidthType.PERCENTAGE } }),
      ],
    }],
  });

  const buffer = await Packer.toBlob(doc);
  saveAs(buffer, `${filename}.docx`);
}

// ─── PowerPoint (.pptx) ─────────────────────────────
export async function exportPowerPoint(data: ExportData, filename: string) {
  const pptxgenjs = await import('pptxgenjs');
  const PptxGenJS = pptxgenjs.default;
  const pptx = new PptxGenJS();

  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = data.meta.generatedBy;
  pptx.title = data.meta.title;

  // ─ Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText(data.meta.title, { x: 0.8, y: 1.2, w: 11, h: 1.2, fontSize: 28, bold: true, color: '1E40AF' });
  titleSlide.addText(
    `Period: ${data.meta.period}  |  Date Range: ${data.meta.dateRange}\nGenerated: ${data.meta.generatedAt}  |  By: ${data.meta.generatedBy}${data.meta.filters ? `\nFilters: ${data.meta.filters}` : ''}`,
    { x: 0.8, y: 2.5, w: 11, h: 1.2, fontSize: 12, color: '64748B' }
  );

  // ─ Summary slide
  const summarySlide = pptx.addSlide();
  summarySlide.addText('Summary', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, bold: true, color: '1E40AF' });

  const summaryHeader = [{ text: 'Metric', options: { bold: true, fill: { color: '1E40AF' }, color: 'FFFFFF', fontSize: 11 } }, { text: 'Value', options: { bold: true, fill: { color: '1E40AF' }, color: 'FFFFFF', fontSize: 11 } }];
  const summaryBody = data.summaryRows.map(r => [
    { text: r.label, options: { fontSize: 10 } },
    { text: String(r.value), options: { fontSize: 10, bold: true } },
  ]);

  summarySlide.addTable([summaryHeader, ...summaryBody] as any, {
    x: 0.5, y: 1.1, w: 8, colW: [5, 3],
    border: { type: 'solid', pt: 0.5, color: 'CBD5E1' },
    rowH: 0.4,
  });

  // ─ Data slides (paginate rows into chunks of 12)
  const ROWS_PER_SLIDE = 12;
  const totalPages = Math.ceil(data.tableRows.length / ROWS_PER_SLIDE);

  for (let p = 0; p < Math.max(totalPages, 1); p++) {
    const dataSlide = pptx.addSlide();
    dataSlide.addText(`Detailed Records${totalPages > 1 ? ` (${p + 1}/${totalPages})` : ''}`, { x: 0.5, y: 0.3, w: 12, h: 0.5, fontSize: 18, bold: true, color: '1E40AF' });

    const headerRow = data.tableHeaders.map(h => ({ text: h, options: { bold: true, fill: { color: '1E40AF' }, color: 'FFFFFF', fontSize: 8 } }));
    const pageRows = data.tableRows.slice(p * ROWS_PER_SLIDE, (p + 1) * ROWS_PER_SLIDE);
    const bodyRows = pageRows.map(row => row.map(cell => ({ text: String(cell ?? ''), options: { fontSize: 8 } })));

    const colCount = data.tableHeaders.length;
    const colW = colCount > 0 ? Array(colCount).fill(12 / colCount) : [12];

    dataSlide.addTable([headerRow, ...bodyRows] as any, {
      x: 0.5, y: 1.0, w: 12, colW,
      border: { type: 'solid', pt: 0.5, color: 'CBD5E1' },
      rowH: 0.35,
      autoPage: false,
    });
  }

  await pptx.writeFile({ fileName: `${filename}.pptx` });
}

// ─── JSON ───────────────────────────────────────────
export function exportJSON(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  saveAs(blob, `${filename}.json`);
}

// ─── Copy to Clipboard ─────────────────────────────
export async function copyToClipboard(data: ExportData): Promise<boolean> {
  const lines = [
    data.meta.title,
    `Period: ${data.meta.period}`,
    `Date Range: ${data.meta.dateRange}`,
    '',
    'Summary:',
    ...data.summaryRows.map(r => `  ${r.label}: ${r.value}`),
    '',
    'Records:',
    data.tableHeaders.join('\t'),
    ...data.tableRows.map(r => r.join('\t')),
  ];
  try {
    await navigator.clipboard.writeText(lines.join('\n'));
    return true;
  } catch {
    return false;
  }
}

// ─── Print ──────────────────────────────────────────
export function printReport() {
  window.print();
}
